name: nfpm

on:
  workflow_dispatch:

jobs:
  nfpm:
    runs-on: ubuntu-latest
    steps:
      -
        name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          install-only: true
      -
        name: Show nfpm version
        run: nfpm -v